### ISSUE TITLE
how do I run this?

### ISSUE THREAD

**Issue by mailinglists35** [Gedsh/Nflog-android#1]

**Comment by Gedsh** [comment]
You can run it on Android in a terminal emulator with root privileges.

**Comment by mailinglists35** [comment]
obviously on root and command line, but could you explain how to setup golang on android? it does seem to be a go thing

**Comment by Gedsh** [comment]
You don't need to install golang on android. Golang does not use a virtual machine. You just need to compile the Android binary on PC. Or you can get a compiled binary from InviZible Pro. It's called libnflog.so. But it's not a library, it's actually a compiled binary that you can run in a terminal emulator.
